package org.example;

import java.util.HashMap;

public class Converter {

    private HashMap<String, HashMap<String, Integer>> typeMap;

    public HashMap<String, Integer> init() {
        HashMap<String, Integer> tempMap = new HashMap<>();
        tempMap.put("Completed", 1);
        tempMap.put("CIP", 2);
        tempMap.put("Land", 3);
        tempMap.put("Completed + CIP", 4);
        tempMap.put("Completed + Land", 5);
        typeMap.put("建成状态", tempMap);
        HashMap<String, Integer> tempMap1 = new HashMap<>();
        tempMap1.put("Bonded", 1);
        tempMap1.put("Non-bonded", 2);
        tempMap1.put("Non-Bonded/Bonded", 3);
        typeMap.put("是否保税", tempMap1);
        HashMap<String, Integer> tempMap2 = new HashMap<>();
        tempMap2.put("冷库", 1);
        tempMap2.put("常温库", 2);
        tempMap2.put("冷库/常温库", 3);
        tempMap2.put("恒温库", 4);
        tempMap2.put("暖库", 5);
        typeMap.put("仓库类型", tempMap2);
        HashMap<String, Integer> tempMap3 = new HashMap<>();
        tempMap3.put("ColdStorage", 1);
        tempMap3.put("ColdStorage&STDWarehouse", 2);
        tempMap3.put("ExportSupervisoryWarehouse", 3);
        tempMap3.put("Warehouse", 4);
        tempMap3.put("Warehouse/ColdStorage", 5);
        tempMap3.put("Warehouse/Workshops", 6);
        tempMap3.put("BTSWarehouse", 7);
        tempMap3.put("Warehouse/port logistics", 8);
        tempMap3.put("Export supervisory ColdStorage", 9);
        typeMap.put("仓库分类", tempMap3);
        HashMap<String, Integer> tempMap4 = new HashMap<>();
        tempMap4.put("单面卸货", 1);
        tempMap4.put("双面卸货", 2);
        tempMap4.put("三面卸货", 3);
        typeMap.put("卸货面", tempMap4);
        HashMap<String, Integer> tempMap5 = new HashMap<>();
        tempMap5.put("丙二类消防", 1);
        tempMap5.put("丙一类消防", 2);
        tempMap5.put("乙类消防", 3);
        tempMap5.put("丙类消防", 4);
        tempMap5.put("戊类消防", 5);
        tempMap5.put("甲类消防", 6);
        typeMap.put("仓库分类", tempMap5);
        HashMap<String, Integer> tempMap6 = new HashMap<>();
        tempMap6.put("是", 1);
        tempMap6.put("否", 2);
        typeMap.put("是否是危险品库", tempMap6);
        HashMap<String, Integer> tempMap7 = new HashMap<>();
        tempMap7.put("是", 1);
        tempMap7.put("否", 2);
        typeMap.put("是否是厂房", tempMap7);
        HashMap<String, Integer> tempMap8 = new HashMap<>();
        tempMap8.put("是", 1);
        tempMap8.put("否", 2);
        typeMap.put("是否有仓配", tempMap8);
        HashMap<String, Integer> tempMap9 = new HashMap<>();
        tempMap9.put("是", 1);
        tempMap9.put("否", 2);
        typeMap.put("是否是高标仓", tempMap9);
        HashMap<String, Integer> tempMap10 = new HashMap<>();
        tempMap10.put("是", 1);
        tempMap10.put("否", 2);
        typeMap.put("是否原房东", tempMap10);
        HashMap<String, Integer> tempMap11 = new HashMap<>();
        tempMap11.put("是", 1);
        tempMap11.put("否", 2);
        typeMap.put("是否近机场", tempMap11);
        HashMap<String, Integer> tempMap12 = new HashMap<>();
        tempMap12.put("是", 1);
        tempMap12.put("否", 2);
        typeMap.put("是否交通便利", tempMap12);
        HashMap<String, Integer> tempMap13 = new HashMap<>();
        tempMap13.put("是", 1);
        tempMap13.put("否", 2);
        typeMap.put("可注册", tempMap13);
        HashMap<String, Integer> tempMap14 = new HashMap<>();
        tempMap14.put("是", 1);
        tempMap14.put("否", 2);
        typeMap.put("要求落税", tempMap14);
        HashMap<String, Integer> tempMap15 = new HashMap<>();
        tempMap15.put("是", 1);
        tempMap15.put("否", 2);
        typeMap.put("是否可分割", tempMap15);
        HashMap<String, Integer> tempMap16 = new HashMap<>();
        tempMap16.put("是", 1);
        tempMap16.put("否", 2);
        typeMap.put("是否有重型机械", tempMap16);
        HashMap<String, Integer> tempMap17 = new HashMap<>();
        tempMap17.put("是", 1);
        tempMap17.put("否", 2);
        typeMap.put("是否有坡道", tempMap17);
        HashMap<String, Integer> tempMap18 = new HashMap<>();
        tempMap18.put("是", 1);
        tempMap18.put("否", 2);
        typeMap.put("是否有斜坡", tempMap18);
        HashMap<String, Integer> tempMap19 = new HashMap<>();
        tempMap19.put("是", 1);
        tempMap19.put("否", 2);
        typeMap.put("是否可分割", tempMap19);
        HashMap<String, Integer> tempMap20 = new HashMap<>();
        tempMap20.put("Business Park", 1);
        tempMap20.put("RP", 2);
        tempMap20.put("Logistics Park", 2);
        typeMap.put("BP/RP/LP", tempMap20);
        HashMap<String, Integer> tempMap21 = new HashMap<>();
        tempMap21.put("地砖", 1);
        tempMap21.put("水泥", 2);
        tempMap21.put("环氧", 3);
        tempMap21.put("耐磨金刚砂", 4);
        typeMap.put("地坪材质", tempMap21);
        HashMap<String, Integer> tempMap22 = new HashMap<>();
        tempMap22.put("工业用地", 1);
        tempMap22.put("物流用地", 2);
        typeMap.put("土地信息", tempMap22);
        HashMap<String, Integer> tempMap23 = new HashMap<>();
        tempMap23.put("国有土地", 1);
        tempMap23.put("集体土地", 2);
        typeMap.put("土地性质", tempMap23);
        HashMap<String, Integer> tempMap24 = new HashMap<>();
        tempMap24.put("可协助", 1);
        tempMap24.put("不可协助", 2);
        typeMap.put("协助办环评", tempMap24);
        HashMap<String, Integer> tempMap25 = new HashMap<>();
        tempMap25.put("大开发商", 1);
        tempMap25.put("本地开发商", 2);
        typeMap.put("开发商属性", tempMap25);
        return tempMap;
    }

}
